export interface TourStep {
  id: string;
  route: string;
  target: string | null;
  placement: "top" | "bottom" | "left" | "right" | "center";
  title: string;
  /** What the audience sees — the headline explanation */
  body: string;
  /** Concrete scenario or example to make it tangible */
  scenario?: string;
  /** Key stats or proof points */
  stats?: string[];
  action?: string;
}

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome",
    route: "/",
    target: null,
    placement: "center",
    title: "MDBA \u2014 The Proactive Atlas Advisor",
    body: "Every Atlas customer above $5K/month has the same problem: no one is watching their clusters around the clock. MDBA changes that.",
    scenario: "Imagine a customer with 12 Atlas clusters across 3 projects. Their monthly bill is $47K. They have no automated way to know if costs are drifting, queries are degrading, or backups are misconfigured. MDBA watches everything and reports back \u2014 like having a senior DBA on call 24/7.",
    stats: [
      "No MongoDB product covers proactive spend intelligence today",
      "Slow queries are the #1 Atlas support ticket category",
      "Backup storage is 30\u201350% of total Atlas spend for data-heavy customers",
    ],
    action: "Start the tour",
  },
  {
    id: "dashboard-savings",
    route: "/",
    target: "[data-tour='savings']",
    placement: "bottom",
    title: "The first thing they see: dollar impact",
    body: "Within 24 hours of connecting, MDBA identifies addressable savings across all clusters. This is real money the customer is leaving on the table.",
    scenario: "This demo estate has 12 clusters. MDBA found $4,210/month in savings \u2014 that\u2019s $50,520/year. The breakdown: $1,520 from data transfer optimization, $1,240 from backup right-sizing, $630 from unused index cleanup, $480 from query optimization, and $340 from pipeline restructuring.",
    stats: [
      "$4,210/mo found automatically \u2014 no human investigation",
      "3 high-severity findings requiring immediate attention",
      "4 automated analysis runs in the last 24 hours",
    ],
  },
  {
    id: "dashboard-findings-preview",
    route: "/",
    target: "[data-tour='top-findings']",
    placement: "left",
    title: "Findings: the proof",
    body: "Each finding is a specific, actionable recommendation \u2014 not a vague alert. MDBA tells you exactly what\u2019s wrong, why it matters, and what to do about it.",
    scenario: "Look at the top finding: \u2018Data transfer costs up 34% week-over-week.\u2019 MDBA doesn\u2019t just flag the spike \u2014 it identifies the 3 collections responsible (user_events, audit_logs, session_data), traces the cause to a new analytics pipeline, and recommends 3 specific fixes with dollar estimates for each.",
    stats: [
      "Each finding includes: root cause, evidence, dollar impact, and fix",
      "Severity ranked: critical \u2192 high \u2192 medium \u2192 low",
      "Security findings flagged separately for compliance review",
    ],
  },
  {
    id: "dashboard-actions",
    route: "/",
    target: "[data-tour='quick-actions']",
    placement: "left",
    title: "Navigation: designed for operators",
    body: "The interface is built for the person who gets the 2am alert. Every action is reachable in one click from the dashboard.",
    scenario: "A DBA opens MDBA in the morning. Dashboard shows 2 new high-severity findings. They click \u2018Review findings,\u2019 approve the index recommendation, dismiss the one they already fixed, and they\u2019re done in 90 seconds.",
  },
  {
    id: "findings-detail",
    route: "/findings",
    target: "[data-tour='findings-summary']",
    placement: "bottom",
    title: "Total impact: the CFO view",
    body: "The findings page opens with the total addressable savings \u2014 both monthly and annualized. This is the number that gets budget approval.",
    scenario: "When the DBA presents to their engineering manager: \u2018MDBA identified $50K/year in savings. The tool costs $6K/year. That\u2019s an 8x return.\u2019 This summary strip gives them that slide.",
    stats: [
      "$4,210/mo addressable = $50,520/year",
      "MDBA subscription: $200\u2013$500/cluster/month",
      "ROI: 8\u201325x depending on estate size",
    ],
  },
  {
    id: "findings-approval",
    route: "/findings",
    target: "[data-tour='findings-list']",
    placement: "top",
    title: "Human-in-the-loop: nothing happens without approval",
    body: "MDBA never makes changes to your cluster automatically. Every recommendation \u2014 especially destructive ones like dropping indexes \u2014 requires explicit human approval.",
    scenario: "The \u2018unused indexes\u2019 finding recommends dropping 18 indexes. MDBA won\u2019t execute that. The DBA clicks \u2018Approve,\u2019 reviews each one, and MDBA only then proceeds. 5 indexes are held back because an ETL job runs monthly.",
    stats: [
      "Approve, Acknowledge, or Dismiss \u2014 3 clear actions",
      "Index drops, TTL changes, and schema modifications are always gated",
      "Full audit trail of who approved what and when",
    ],
  },
  {
    id: "agent-reasoning",
    route: "/findings",
    target: "[data-tour='findings-list']",
    placement: "top",
    title: "Agent reasoning trail: how savings are calculated",
    body: "Expand any finding to see the full agent audit trail \u2014 a step-by-step chain of tool calls, data retrieved, analysis, and conclusions. This is the transparency layer that makes findings credible and auditable.",
    scenario: "Expand the \u2018Backup costs increased 22%\u2019 finding. The reasoning trail shows: (1) Agent decides to pull billing data, (2) Tool calls the Atlas Admin API for invoice line items, (3) Data shows backup storage grew from $5,482 to $6,695, (4) Agent traces the cause to hourly snapshots on staging-west and 18% growth on prod-east-1, (5) Conclusion: $1,213/mo addressable by right-sizing snapshot intervals. Every number is traceable to a specific API call.",
    stats: [
      "4 reasoning roles: agent (thinking), tool (API calls), data (what came back), conclusion (the recommendation)",
      "Each finding has its own reasoning trace \u2014 no black boxes",
      "This is the RAG-style audit trail that compliance teams need",
      "Same trace structure whether generated by a workflow or a flow",
    ],
  },
  {
    id: "workflows-overview",
    route: "/workflows",
    target: "[data-tour='workflows']",
    placement: "bottom",
    title: "Workflows: the engine behind findings",
    body: "Every finding is generated by a workflow \u2014 an automated pipeline that runs on a schedule. Workflows can be run, viewed, deleted, or promoted to the visual flow editor for advanced customization.",
    scenario: "This estate has 3 workflows: (1) Cost & query health runs hourly on the production cluster, (2) Backup & index rationalization runs daily across all 12 clusters, (3) Security & data quality runs every 4 hours on the fintech tier. Each generates findings automatically. If a workflow needs custom logic \u2014 like conditional Slack alerts or multi-step API chains \u2014 click \u2018Open in flow editor\u2019 to graduate to the visual canvas.",
    stats: [
      "Workflows follow a 4-stage pipeline: Ingest \u2192 Analyze \u2192 Synthesize \u2192 Deliver",
      "Trigger options: manual, scheduled (cron), or change-stream driven",
      "Full lifecycle management: run, view, delete, or promote to flow editor",
      "Deleting a workflow cascades to its runs and findings",
    ],
  },
  {
    id: "workflow-drill-in",
    route: "/workflows/wf-cost-query",
    target: "[data-tour='workflow-pipeline']",
    placement: "bottom",
    title: "Drill in: live pipeline simulation",
    body: "Click into any workflow to see its full configuration, run it live, or open it in the visual flow editor. The pipeline visualization animates each stage in real time as data flows through.",
    scenario: "This is the Cost & Query Health workflow for prod-east-1. Click \u2018Run workflow\u2019 and watch: the ingest stage pulls Atlas billing data, the spend agent detects a 34% cost spike, the slow query agent finds a COLLSCAN on 2.4M documents, the synthesizer ranks by impact, and deliver publishes to inbox. Need more control? Click \u2018Open in flow editor\u2019 to convert these steps into a visual DAG where you can add conditional logic, Slack alerts, or custom tool chains.",
    stats: [
      "Each step shows its agent type, configuration parameters, and description",
      "Execution log streams live \u2014 every API call, every analysis, every result",
      "Findings appear inline after the run with severity, dollar impact, and recommendations",
      "\u2018Open in flow editor\u2019 converts agent steps to visual canvas nodes \u2014 start simple, graduate to advanced",
    ],
  },
  {
    id: "workflow-steps-detail",
    route: "/workflows/wf-cost-query",
    target: "[data-tour='workflow-steps']",
    placement: "top",
    title: "Agent steps: what MDBA actually does",
    body: "Each workflow has one or more agent steps. An agent is a specialized analyzer \u2014 spend monitoring, slow query detection, backup rationalization, index cleanup, security analysis, or data quality checks.",
    scenario: "Step 1 is the Spend agent: it pulls 30 days of Atlas billing data and computes a rolling average. If current spend deviates more than 15%, it generates a finding with the exact collections driving the increase. Step 2 is the Slow Query agent: it queries system.profile for operations above 100ms and runs explain to identify missing indexes.",
    stats: [
      "7 agent types available: spend, slow_query, backup, index_rationalization, security, data_quality, scaling",
      "Each agent has configurable parameters (thresholds, lookback windows, dedup hours)",
      "Agents can be chained \u2014 e.g., spend + slow_query in a single workflow",
    ],
  },
  {
    id: "create-simple",
    route: "/create",
    target: "[data-tour='outcomes']",
    placement: "right",
    title: "Create a workflow in 10 seconds",
    body: "The simple builder is designed so that any operator \u2014 not just a DBA expert \u2014 can set up monitoring. Check what to watch, pick how often, save.",
    scenario: "A new customer connects their cluster. They check \u2018Costs & usage,\u2019 \u2018App speed,\u2019 and \u2018Backups.\u2019 They pick \u2018Once a day.\u2019 That\u2019s it \u2014 tomorrow morning they\u2019ll have their first findings. The whole setup took 10 seconds.",
    stats: [
      "7 monitoring categories: cost, performance, backups, security, data quality, capacity, indexes",
      "3 schedule options: manual, daily, hourly",
      "Advanced mode available for custom agent chains",
    ],
  },
  {
    id: "advisor-chat",
    route: "/advisor",
    target: "[data-tour='chat']",
    placement: "top",
    title: "Natural language: describe what you need",
    body: "The advisor understands Atlas-specific requests and drafts complete workflows. It uses MongoDB Agent Skills to avoid incorrect recommendations.",
    scenario: "A user types: \u2018Monitor my spend and alert me if data transfer costs spike above 20%.\u2019 The advisor creates a workflow with a spend agent (baseline_days: 30, threshold_pct: 20), schedules it hourly, and presents it for one-click save.",
    stats: [
      "Powered by GPT-4o-mini with MongoDB Agent Skills context",
      "Falls back to a built-in heuristic when no API key is configured",
      "Generates structured workflow JSON \u2014 not just text advice",
    ],
  },
  {
    id: "flow-editor",
    route: "/advisor/flow",
    target: "[data-tour='flow-canvas']",
    placement: "right",
    title: "Visual flow editor: the 20% path",
    body: "For the corner cases that the simple builder can\u2019t express, the flow editor provides a visual canvas for building multi-step tool chains. Workflows can be promoted here, and flows can persist real findings back to the inbox.",
    scenario: "This is a backup cost monitor flow with 4 steps: (1) Atlas API call to pull invoices, (2) Atlas API details for line items, (3) MDBA reasoning to compute the delta, (4) Slack alert if the threshold is exceeded. Click \u2018Save findings\u2019 and the flow generates the same findings and audit trail as a workflow \u2014 they show up on the dashboard and in the findings inbox.",
    stats: [
      "Drag-and-drop tool palette: Atlas API, MongoDB, MDBA, Slack, Email",
      "Each node has a natural-language prompt and optional prior-step memory",
      "\u2018Save findings\u2019 persists simulated findings to the inbox \u2014 flows are first-class",
      "Workflows can be promoted here via \u2018Open in flow editor\u2019 for advanced customization",
    ],
  },
  {
    id: "flow-terminal",
    route: "/advisor/flow",
    target: "[data-tour='flow-terminal']",
    placement: "left",
    title: "Execution terminal: see every API call",
    body: "Click \u2018Run\u2019 and the terminal streams the execution in real time. Every step shows the agent\u2019s reasoning, the actual API call it would make, the response payload, and a summary of what it found.",
    scenario: "Watch the backup monitor flow execute: Step 1 calls the Atlas invoices endpoint and gets back 2 invoices with line-item breakdown. Step 2 drills into each invoice for backup costs by cluster. Step 3 computes a $1,213/mo increase (+22.1%) and identifies 3 contributing factors. Step 4 composes a Slack message with a \u2018Review in MDBA\u2019 button \u2014 only because the delta exceeded the $1,000 threshold.",
    stats: [
      "NDJSON streaming from the API \u2014 output appears line by line as it executes",
      "JSON payloads are syntax-highlighted and expandable",
      "Built-in commands: help, run, list, edges, clear, abort",
      "All execution is simulated in the PoC \u2014 no live Atlas calls unless connected",
    ],
  },
  {
    id: "history-audit",
    route: "/runs",
    target: "[data-tour='runs']",
    placement: "bottom",
    title: "Full audit trail: compliance-ready",
    body: "Every automated analysis is recorded with timestamps, trace steps, and results. This is the audit trail that enterprise compliance teams require.",
    scenario: "An auditor asks: \u2018What automated changes were made to the production cluster last quarter?\u2019 The DBA pulls up the run history \u2014 every analysis, every finding, every approval. Nothing was modified without human sign-off. Full traceability.",
    stats: [
      "Each run records: start time, pipeline stages, findings produced, completion time",
      "Trace shows exactly what data was collected and what was analyzed",
      "Stored in MongoDB \u2014 queryable, exportable, retention-configurable",
    ],
  },
  {
    id: "settings-connect",
    route: "/settings",
    target: null,
    placement: "center",
    title: "Connect in 30 seconds",
    body: "Settings lets you connect to any Atlas cluster and optionally add an OpenAI API key. Connection is validated before proceeding. Credentials stay in server memory \u2014 never written to disk.",
    scenario: "During a customer meeting: \u2018Let me connect to your cluster right now.\u2019 Paste the connection string, click Test \u2014 \u2018Connected to Cluster0 (v7.0.12).\u2019 Reset the demo data and now all findings are being generated against their actual estate.",
    stats: [
      "Supports mongodb+srv:// and standard connection strings",
      "OpenAI key enables GPT-powered advisor (optional)",
      "Demo data reset button for fresh presentations",
    ],
  },
  {
    id: "business-case",
    route: "/",
    target: null,
    placement: "center",
    title: "The business case for MongoDB",
    body: "MDBA isn\u2019t about helping customers spend less on Atlas \u2014 it\u2019s about removing the fear of scaling. Customers who understand their spend deploy more confidently and grow faster.",
    scenario: "AWS learned this with Trusted Advisor: giving customers visibility into spend increased AWS revenue because it removed the fear of scaling. MDBA does the same for Atlas.",
    stats: [
      "Revenue model: $200\u2013$500/cluster/month (net-new ARR on top of Atlas)",
      "Retention: customers who understand their bill don\u2019t migrate to Postgres",
      "Support cost: fewer P1 tickets (slow queries are #1 category today)",
      "Expansion: customers who see ROI from monitoring add more clusters",
    ],
  },
  {
    id: "complete",
    route: "/",
    target: null,
    placement: "center",
    title: "MDBA: an AI co-pilot for every Atlas cluster",
    body: "What happens when you give every Atlas cluster an AI advisor that never sleeps? Customers find waste they didn\u2019t know about, prevent incidents before they happen, and every operator feels like they have a senior DBA at their side.",
    stats: [
      "Every Atlas customer above $5K/month is a potential buyer",
      "First demo sells itself: \u2018Here\u2019s what we found on your cluster in 24 hours\u2019",
      "Built on MongoDB, for MongoDB \u2014 proves AI + MDB work together credibly",
    ],
    action: "Finish tour",
  },
];
